/* tslint:disable */
/* eslint-disable */
/**
 * Stamp API
 * Stamp API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInRequest
 */
export interface LogInRequest {
    /**
     * 
     * @type {string}
     * @memberof LogInRequest
     */
    authProvider: string;
    /**
     * 
     * @type {string}
     * @memberof LogInRequest
     */
    accessToken: string;
}

/**
 * Check if a given object implements the LogInRequest interface.
 */
export function instanceOfLogInRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authProvider" in value;
    isInstance = isInstance && "accessToken" in value;

    return isInstance;
}

export function LogInRequestFromJSON(json: any): LogInRequest {
    return LogInRequestFromJSONTyped(json, false);
}

export function LogInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authProvider': json['authProvider'],
        'accessToken': json['accessToken'],
    };
}

export function LogInRequestToJSON(value?: LogInRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authProvider': value.authProvider,
        'accessToken': value.accessToken,
    };
}

