/* tslint:disable */
/* eslint-disable */
/**
 * Stamp API
 * Stamp API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInResponse
 */
export interface LogInResponse {
    /**
     * 
     * @type {string}
     * @memberof LogInResponse
     */
    jwt: string;
}

/**
 * Check if a given object implements the LogInResponse interface.
 */
export function instanceOfLogInResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "jwt" in value;

    return isInstance;
}

export function LogInResponseFromJSON(json: any): LogInResponse {
    return LogInResponseFromJSONTyped(json, false);
}

export function LogInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jwt': json['jwt'],
    };
}

export function LogInResponseToJSON(value?: LogInResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jwt': value.jwt,
    };
}

