/* tslint:disable */
/* eslint-disable */
/**
 * Stamp API
 * Stamp API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPostRequest
 */
export interface PostPostRequest {
    /**
     * 
     * @type {string}
     * @memberof PostPostRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostPostRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PostPostRequest
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof PostPostRequest
     */
    rootDomain: string;
}

/**
 * Check if a given object implements the PostPostRequest interface.
 */
export function instanceOfPostPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "link" in value;
    isInstance = isInstance && "rootDomain" in value;

    return isInstance;
}

export function PostPostRequestFromJSON(json: any): PostPostRequest {
    return PostPostRequestFromJSONTyped(json, false);
}

export function PostPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'link': json['link'],
        'rootDomain': json['rootDomain'],
    };
}

export function PostPostRequestToJSON(value?: PostPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'link': value.link,
        'rootDomain': value.rootDomain,
    };
}

